### ISSUE TITLE
Allow passing arguments to `lutaml_uml_datamodel_description` via options hash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#50]
Right now the syntax for data model description is:

```
[lutaml_uml_datamodel_description,../../xmi-full/full-242.xmi,lutaml_packages.yml]
----
...
```

But it requires a YAML file like this:

```yaml
packages:
  - "Core"
  - "Appearance"
  - "CityFurniture"
  - "CityObjectGroup"
  - ...
section_depth: 3
render_style: entity_list
```

I think we should accept a hash in the command to allow specification of
* `section_depth=3`
* `style=entity_list`; and
* `packages=Core,Appearance,xxx`
