### ISSUE TITLE
Add mechanism to allow linking anchors for XMI defined objects that are not generated in document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-plugin-lutaml#70]
From https://github.com/metanorma/ogc-citygml-xmi/issues/110

In the CityGML 3.0 XMI file, the following classes are used (by other classes) but not defined because they are out of scope:
```
Area
Boolean
Character
CharacterString
Date
DateTime
EngineeringCRS
GenericName
Integer
Length
Measure
Real
ScopedName
TM_Duration
URI
UnitOfMeasure
Volume
```

However, the plugin today creates links to these anchors but they are not present in the current document:
```adoc
Area-section
Boolean-section
Character-section
CharacterString-section
Date-section
DateTime-section
EngineeringCRS-section
GenericName-section
Integer-section
Length-section
Measure-section
Real-section
ScopedName-section
TM_Duration-section
URI-section
UnitOfMeasure-section
Volume-section
```

This means we need to have a YAML configuration that "defines where the classes that are out of scope should link to", e.g.

```yaml
packages:
  - "Core"
  - "Appearance"
external_classes:
  - "Area": {{Area}}
  - "Boolean": my-section-for-boolean
  - ...
section_depth: 3
render_style: data_dictionary
include_root: true
```
